// Generates the web app's Material 3 palette CSS (app/theme.css).
//
// Hora family web design language: **neutral surfaces + uniform accents**. The
// canonical --md-* VALUES (the monochrome neutral surface scale + the uniform
// family accent) live in hora-core at shared/web/res/theme-palette.mjs — synced
// into this app as scripts/theme-palette.mjs and imported below. This script
// applies those values across light/dark and emits theme.css with Muthal's own
// data-theme toggle selectors. (Any role not in the palette falls back to a
// generated M3 scheme seeded from the brand colour.)
//
// Re-run:  node scripts/gen-theme-run.mjs   (or: npm run gen-theme)
// Output: app/theme.css (generated; do not hand-edit).

import {
  argbFromHex,
  hexFromArgb,
  Hct,
  SchemeTonalSpot,
  SchemeNeutral,
  MaterialDynamicColors,
} from "@material/material-color-utilities";
import { writeFileSync } from "node:fs";
import { LIGHT as PURE_NEUTRAL_LIGHT, DARK as PURE_NEUTRAL_DARK } from "./theme-palette.mjs";

const SEED = "#445353"; // Muthal brand icon text colour (Hora family slate)

const ROLES = [
  "primary", "onPrimary", "primaryContainer", "onPrimaryContainer",
  "secondary", "onSecondary", "secondaryContainer", "onSecondaryContainer",
  "tertiary", "onTertiary", "tertiaryContainer", "onTertiaryContainer",
  "error", "onError", "errorContainer", "onErrorContainer",
  "background", "onBackground",
  "surface", "onSurface", "surfaceVariant", "onSurfaceVariant",
  "surfaceDim", "surfaceBright",
  "surfaceContainerLowest", "surfaceContainerLow", "surfaceContainer",
  "surfaceContainerHigh", "surfaceContainerHighest",
  "outline", "outlineVariant",
  "inverseSurface", "inverseOnSurface", "inversePrimary",
  "scrim", "shadow",
];

const ACCENT_ROLES = new Set([
  "primary", "onPrimary", "primaryContainer", "onPrimaryContainer",
  "secondary", "onSecondary", "secondaryContainer", "onSecondaryContainer",
  "tertiary", "onTertiary", "tertiaryContainer", "onTertiaryContainer",
  "error", "onError", "errorContainer", "onErrorContainer",
  "inversePrimary",
]);

const mdc = MaterialDynamicColors;
const kebab = (s) => s.replace(/[A-Z]/g, (m) => "-" + m.toLowerCase());

function vars(accent, neutral, isDark) {
  const overrides = isDark ? PURE_NEUTRAL_DARK : PURE_NEUTRAL_LIGHT;
  return ROLES.map((r) => {
    if (overrides[r] !== undefined) {
      return `  --md-${kebab(r)}: ${overrides[r]};`;
    }
    const dc = mdc[r];
    if (!dc || typeof dc.getArgb !== "function") return null;
    const scheme = ACCENT_ROLES.has(r) ? accent : neutral;
    return `  --md-${kebab(r)}: ${hexFromArgb(dc.getArgb(scheme))};`;
  })
    .filter(Boolean)
    .join("\n");
}

const seed = Hct.fromInt(argbFromHex(SEED));
const light = vars(
  new SchemeTonalSpot(seed, false, 0),
  new SchemeNeutral(seed, false, 0),
  false
);
const dark = vars(
  new SchemeTonalSpot(seed, true, 0),
  new SchemeNeutral(seed, true, 0),
  true
);

const css = `/* GENERATED by scripts/gen-theme.mjs — Material 3 palette: slate accent (seeded
 * from the Muthal brand icon ${SEED}) over neutral surfaces (Hora family web
 * design language). Re-run \`npm run gen-theme\` to regenerate. Do not edit by hand. */
:root {
${light}
}
:root[data-theme="dark"] {
${dark}
}
@media (prefers-color-scheme: dark) {
  :root[data-theme="system"] {
${dark}
  }
}
`;

writeFileSync(new URL("../app/theme.css", import.meta.url), css);
console.error("✓ wrote app/theme.css");
